backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Page d'Accueil (Index)"
        file: "admin/home.json"
        fields:
          - label: "Mode Crêpe"
            name: "crepe"
            widget: "object"
            fields:
              - {label: "Titre", name: "brand", widget: "string"}
              - {label: "Sous-titre", name: "subtitle", widget: "string"}
              - {label: "Description", name: "desc", widget: "text"}
              - {label: "Couleur Accent", name: "accentColor", widget: "color"}
              - {label: "Image de Fond", name: "heroImage", widget: "image"}
              - label: "Menu"
                name: "menu"
                widget: "list"
                fields:
                  - {label: "Nom", name: "title", widget: "string"}
                  - {label: "Prix", name: "price", widget: "string"}
                  - {label: "Description", name: "desc", widget: "text"}
                  - {label: "Image", name: "img", widget: "image"}
              - label: "Suppléments"
                name: "supplements"
                widget: "list"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Prix", name: "price", widget: "string"}
                  - {label: "Liste", name: "items", widget: "list", field: {name: "item", widget: "string"}}
          
          - label: "Mode Chicken"
            name: "chicken"
            widget: "object"
            fields:
              - {label: "Titre", name: "brand", widget: "string"}
              - {label: "Sous-titre", name: "subtitle", widget: "string"}
              - {label: "Description", name: "desc", widget: "text"}
              - {label: "Couleur Accent", name: "accentColor", widget: "color"}
              - {label: "Image de Fond", name: "heroImage", widget: "image"}
              - label: "Menu"
                name: "menu"
                widget: "list"
                fields:
                  - {label: "Nom", name: "title", widget: "string"}
                  - {label: "Prix", name: "price", widget: "string"}
                  - {label: "Description", name: "desc", widget: "text"}
                  - {label: "Image", name: "img", widget: "image"}
              - label: "Desserts"
                name: "desserts"
                widget: "list"
                fields:
                  - {label: "Nom", name: "title", widget: "string"}
                  - {label: "Prix", name: "price", widget: "string"}
                  - {label: "Description", name: "desc", widget: "text"}
                  - {label: "Image", name: "img", widget: "image"}
              - label: "Suppléments"
                name: "supplements"
                widget: "list"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Prix", name: "price", widget: "string"}
                  - {label: "Liste", name: "items", widget: "list", field: {name: "item", widget: "string"}}

      - name: "compose"
        label: "Page Compose Ta Crêpe"
        file: "admin/compose.json"
        fields:
          - label: "Coté Salé"
            name: "sale"
            widget: "object"
            fields:
              - {label: "Prix de base", name: "basePrice", widget: "string"}
              - label: "Sections"
                name: "sections"
                widget: "object"
                fields: 
                  - label: "Viandes (Proteins)"
                    name: "proteins"
                    widget: "object"
                    fields:
                      - {label: "Titre", name: "title", widget: "string"}
                      - {label: "Prix", name: "price", widget: "string"}
                      - label: "Ingrédients"
                        name: "items"
                        widget: "list"
                        fields: [{label: "Nom", name: "name", widget: "string"}, {label: "Image", name: "img", widget: "image"}]
                  - label: "Légumes (Veggies)"
                    name: "veggies"
                    widget: "object"
                    fields:
                      - {label: "Titre", name: "title", widget: "string"}
                      - {label: "Prix", name: "price", widget: "string"}
                      - label: "Ingrédients"
                        name: "items"
                        widget: "list"
                        fields: [{label: "Nom", name: "name", widget: "string"}, {label: "Image", name: "img", widget: "image"}]
                  - label: "Fromages (Cheeses)"
                    name: "cheeses"
                    widget: "object"
                    fields:
                      - {label: "Titre", name: "title", widget: "string"}
                      - {label: "Prix", name: "price", widget: "string"}
                      - label: "Ingrédients"
                        name: "items"
                        widget: "list"
                        fields: [{label: "Nom", name: "name", widget: "string"}, {label: "Image", name: "img", widget: "image"}]
                  - label: "Sauces"
                    name: "sauces"
                    widget: "object"
                    fields:
                      - {label: "Titre", name: "title", widget: "string"}
                      - {label: "Prix", name: "price", widget: "string"}
                      - label: "Ingrédients"
                        name: "items"
                        widget: "list"
                        fields: [{label: "Nom", name: "name", widget: "string"}, {label: "Image", name: "img", widget: "image", required: false}]
          - label: "Coté Sucré"
            name: "sucre"
            widget: "object"
            fields:
              - {label: "Prix de base", name: "basePrice", widget: "string"}
              - label: "Sections"
                name: "sections"
                widget: "object"
                fields: 
                  - label: "Basics"
                    name: "basics"
                    widget: "object"
                    fields:
                      - {label: "Titre", name: "title", widget: "string"}
                      - {label: "Prix", name: "price", widget: "string"}
                      - label: "Ingrédients"
                        name: "items"
                        widget: "list"
                        fields: [{label: "Nom", name: "name", widget: "string"}, {label: "Image", name: "img", widget: "image"}]
                  - label: "Gourmandises"
                    name: "gourmandises"
                    widget: "object"
                    fields:
                      - {label: "Titre", name: "title", widget: "string"}
                      - {label: "Prix", name: "price", widget: "string"}
                      - label: "Ingrédients"
                        name: "items"
                        widget: "list"
                        fields: [{label: "Nom", name: "name", widget: "string"}, {label: "Image", name: "img", widget: "image"}]
                  - label: "Fruits"
                    name: "fruits"
                    widget: "object"
                    fields:
                      - {label: "Titre", name: "title", widget: "string"}
                      - {label: "Prix", name: "price", widget: "string"}
                      - label: "Ingrédients"
                        name: "items"
                        widget: "list"
                        fields: [{label: "Nom", name: "name", widget: "string"}, {label: "Image", name: "img", widget: "image"}]